steps:
  # Build the Docker image with BuildKit
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'buildx'
      - 'build'
      - '--platform=linux/amd64'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/finops/finops-pipeline:latest'
      - '--push'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/finops/finops-pipeline:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
